name: sync-client

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  sync-client:
    runs-on: ubuntu-slim

    steps:
      - name: Set up checkout
        uses: actions/checkout@v6

      - name: Set up environment variables
        run: echo "SHORT_SHA=${GITHUB_SHA:0:7}" >> $GITHUB_ENV

      - name: Sync
        uses: BetaHuhn/repo-file-sync-action@v1
        with:
          GH_PAT: ${{ secrets.GH_PAT }}
          CONFIG_PATH: .github/${{ github.workflow }}.yml
          PR_LABELS: ${{ github.workflow }}
          ASSIGNEES: ${{ github.repository_owner }}
          COMMIT_PREFIX: 'chore(${{ github.workflow }}):'
          PR_BODY: '@${{ github.repository_owner }} check out [`${{ env.SHORT_SHA }}`](https://github.com/${{ github.repository }}/commit/${{ github.sha }}).üê£'
